basePath: /
definitions:
  models.Aluno:
    properties:
      id:
        type: integer
      idade:
        type: integer
      nome:
        type: string
      nomeProfessor:
        type: string
      notaPrimeiroSemestre:
        type: number
      notaSegundoSemestre:
        type: number
      numeroSala:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gerenciar alunos em uma escola.
  title: Escola CRUD API
  version: "1.0"
paths:
  /alunos:
    get:
      description: Retorna todos os alunos cadastrados no banco de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Aluno'
            type: array
      summary: Lista todos os alunos
      tags:
      - alunos
    post:
      consumes:
      - application/json
      description: Adiciona um novo aluno ao banco de dados
      parameters:
      - description: Dados do aluno
        in: body
        name: aluno
        required: true
        schema:
          $ref: '#/definitions/models.Aluno'
      produces:
      - application/json
      responses:
        "201":
          description: Aluno criado com sucesso!
          schema:
            type: string
        "400":
          description: Erro na criação do aluno
          schema:
            type: string
      summary: Cria um novo aluno
      tags:
      - alunos
  /alunos/{id}:
    delete:
      description: Exclui um aluno específico do banco de dados
      parameters:
      - description: ID do aluno
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Aluno removido com sucesso!
          schema:
            type: string
        "400":
          description: Erro na remoção do aluno
          schema:
            type: string
      summary: Remove um aluno
      tags:
      - alunos
    put:
      consumes:
      - application/json
      description: Atualiza as informações de um aluno específico no banco de dados
      parameters:
      - description: ID do aluno
        in: path
        name: id
        required: true
        type: integer
      - description: Dados atualizados do aluno
        in: body
        name: aluno
        required: true
        schema:
          $ref: '#/definitions/models.Aluno'
      produces:
      - application/json
      responses:
        "200":
          description: Aluno atualizado com sucesso!
          schema:
            type: string
        "400":
          description: Erro na atualização do aluno
          schema:
            type: string
      summary: Atualiza um aluno existente
      tags:
      - alunos
swagger: "2.0"
